### ISSUE TITLE
CORS failure

### ISSUE THREAD

**Issue by marksto** [jsoma/tabletop#150]
Hello, Jonathan.

I strangely get an **"Failed to load ... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access"** error message with Tabletop today.

My spreadsheet is 100% new, public and directly accessible. Playing around with its access rights and generated URLs (as you described in [README](https://github.com/jsoma/tabletop#if-your-publish-to-web-url-doesnt-work)) doesn't seem to help.

Did Google change its CORS policy for public sheets?
Can you, please, check it playing with Tabletop request headers?

Thanks in advance!

Cheers,
Mark.

**Comment by marksto** [comment]
**UPD.** Found out that Spreadsheet is also to be in a _Published to the Web_ state (see this [blog](https://ctrlq.org/code/20004-google-spreadsheets-json)). It generates another type of link, _with_ "/d/e" fragment you've mentioned in README, i.e. "https://docs.google.com/spreadsheets/d/e/${2PAXC-SHEET-ID}/pub?output=csv".

Still, Tabletop gives the same old CORS error. =/

Nevertheless, a simple as hell jQuery AJAX request
`$.ajax({
    type: 'GET',
    url: publishedSheetURL
});`
gives the expected result, even at localhost.

**Comment by mike820324** [comment]
Hi, 
I also encounter this problem, and I have manage a way to work around this issue. 
The following are the steps that I took,
1. Get the share link from the top right corner share button. (The permission that I use is **anyone with the link can view**)
2. Go to **File** -> **Publish to the Web** and publish the spreadsheet.
3. use the link from step 1 and paste to the javascript code.

It seems like in order to let the link worked, the following are required
- use the share link from step 1
- published the spread sheet from step 2.

Hope this will help.

**Comment by davidelrizzo** [comment]
Thank you, I tried everything and only that exact 3 step procedure stopped the CORS error!

**Comment by mroswell** [comment]
I reported the following in August 2017. In my case, copying the whole link from share doesn't work. I have to grab just the ID
https://github.com/jsoma/tabletop/issues/147#issuecomment-326151962

**Comment by bacharakis** [comment]
Just tried @mike820324 comment and it worked pretty well.
Thank you

**Comment by bacharakis** [comment]
@mroswell let's show them some love then and update them :D

**Comment by mroswell** [comment]
Would rather have an authoritative voice. Though I offer my comments in various threads as helpful resources, I'm just not equipped right now to be the authoritative voice.

**Comment by jsoma** [comment]
Updated the docs to reflect the miserable world we live in, now says you must both publish **and** share. Hope this helps!
