### ISSUE TITLE
how to show alert if wrong spreadsheet URL?

### ISSUE THREAD

**Issue by jmcausing** [jsoma/tabletop#151]
Hi guys,

I created an input for me to enter the spreadsheet URL. If I enter the spreadsheet with correct URL, it shows all what I need.

But how can I catch the error in console.log if URL is not correct?

or how to alert if the user enters the wrong URL?

**Comment by thaddeusm** [comment]
This issue almost made the library unusable for me.  I threw in another listener for errors during the request so that I could provide some feedback to the user.

Try adding something like this to the source (tabletop.js) at around line 197:
`xlr.addEventListener('error', function() { console.log('error') };`
