### ISSUE TITLE
error while putting sheet url

### ISSUE THREAD

**Issue by mukesh551** [jsoma/tabletop#183]
main.js?attr=iAfsT-K7U4kMN2MyBwm_w2sWjVfCX2Uyp2i7FkZQ-anzH3-GC6H5dfXlY3Qf1_THADfTO-p_r6b9mjsaP2grOw:1061 GET https://spreadsheets.google.com/feeds/worksheets/e/2PACX-1vS5NvsaHZovoYeTzJ7rRqe5jsuRrdx5XnJVsIAZtQVdFzJ57wwaKR9EZBC_WZLrUVPj3um0h2PeP9zH/public/basic?alt=json 404
window.XMLHttpRequest.send @ main.js?attr=iAfsT-K7U4kMN2MyBwm_w2sWjVfCX2Uyp2i7FkZQ-anzH3-GC6H5dfXlY3Qf1_THADfTO-p_r6b9mjsaP2grOw:1061
xhrFetch @ tabletop.js:201
requestData @ tabletop.js:177
fetch @ tabletop.js:159
h @ tabletop.js:137
h.init @ tabletop.js:146
init @ 1url&pdfupdate.html:21
Show 1 more frame
tabletop.js:197 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.s.onload (tabletop.js:195)
s.onload @ tabletop.js:197
load (async)
xhrFetch @ tabletop.js:192
requestData @ tabletop.js:177
fetch @ tabletop.js:159
h @ tabletop.js:137
h.init @ tabletop.js:146
init @ 1url&pdfupdate.html:21
Show 1 more frame
tabletop.js:327 Uncaught TypeError: Cannot read property 'feed' of undefined
    at h.loadSheets (tabletop.js:327)
    at XMLHttpRequest.s.onload (tabletop.js:199)

**Comment by njlatcham** [comment]
tabletop.min.js:formatted:154 Uncaught TypeError: Cannot read property 'length' of undefined
    at h.loadSheets.

I think I am getting the same type of error here, where it reaches the loadSheets function, and in the loop, n = t.feed.entry.length, something isn't defined. Im not sure what the issue is here but it wasn't happening a week ago, and as I try to create new spreadsheets this is the error I always get. With my previous spreadsheet from last week, everything seems to work fine.

**Comment by jsoma** [comment]
I'll note here that it's probably worth looking at #184 for people who are having similar trouble. It looks like it's a game of picking the right options when publishing (or re-publishing?) sheets.
