### ISSUE TITLE
Keeping speadsheet colum order in ng-repeat

### ISSUE THREAD

**Issue by tomdavidson** [jsoma/tabletop#83]
Hello, I ried to useing ng-repeat to set a table header, but there is no control of the order with ng-orderBy since the data from tabletop is an array of objects. ngOrderObjectBy would allow an ordering based on key, but still nothing to give me the same order as in the source spreadsheet.

How do I preserve the colum order from the Google Spreadsheet?

**Comment by aendrew** [comment]
I've run into this before too. There's no way AFAIK due to the fact that objects have no particular order within JS. Might be nice to have a "return as an array of arrays" option somewhere, but I can see that creating really hard-to-read code. Why not just do some stuff with `Array.prototype.map` inside AngularJS to process the data a certain way before attaching it to `$scope`?
